In [1]:
import numpy as np
import pandas as pd

In [11]:
all_fighters = pd.read_csv('/Users/amap3i/Library/CloudStorage/OneDrive-GrandValleyStateUniversity/CIS_671/Final Project/fighters.csv')

In [17]:
all_fighters['total_wins'].describe()

count    614.000000
mean       1.674267
std        4.038326
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max       30.000000
Name: total_wins, dtype: float64

In [14]:
all_fighters

,name,win_ratio,total_fights,sub_win_ratio,point_win_ratio,decision_win_ratio,n_editions_competed,scored_points_per_fight,suffered_points_per_fight,fights_per_edition,...,n_different_subs,fought_superfight,total_wins,debut_year,female,city,state,country,latitude,longitude
0,Nick Rodriguez,0.700000,10.0,0.100000,0.400000,0.200000,4.0,2.300000,-0.200000,2.500,...,1,0,7.0,2019,0,Philadelphia,Pennsylvania,USA,39.952724,-75.163526
1,Orlando Sanchez,0.692308,13.0,0.153846,0.153846,0.384615,8.0,-0.384615,-0.461538,1.625,...,2,0,9.0,2013,0,Los Angeles,California,USA,34.053691,-118.242766
2,Paul Schreiner,0.500000,4.0,0.000000,0.500000,0.000000,2.0,1.250000,-0.500000,2.000,...,0,0,2.0,2022,0,Santa Cruz,California,USA,37.050096,-121.990590
3,David Terrell,0.750000,4.0,0.250000,0.500000,0.000000,2.0,-1.000000,-1.000000,2.000,...,1,0,3.0,2003,0,Santa Rosa,California,USA,38.440492,-122.714105
4,Eddie Bravo,0.666667,3.0,0.666667,0.000000,0.000000,2.0,-0.666667,4.666667,1.500,...,2,0,2.0,2003,0,Santa Ana,California,USA,33.749495,-117.873221
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,K. Toida,0.000000,1.0,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,1.000,...,0,0,0.0,2003,0,Tokyo,NaN,Japan,35.676860,139.763895
610,Manu Garcia,0.000000,1.0,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,1.000,...,0,0,0.0,2000,0,Barcelona,NaN,Spain,41.382894,2.177432
611,Jesse Urholin,0.000000,1.0,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,1.000,...,0,0,0.0,2017,0,Helsinki,NaN,Finland,60.167488,24.942747
612,Rodrigo Caporal,0.000000,1.0,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,1.000,...,0,0,0.0,2013,0,Santos,NaN,Brazil,-23.933599,-46.328640
613,Mayssa Bastos,0.000000,1.0,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,1.000,...,0,0,0.0,2022,1,Niterói,NaN,Brazil,-22.888400,-43.114700

In [15]:
all_fighters_gt_2 = all_fighters[all_fighters['total_wins'] >= 2]
all_fighters_gt_2

,name,win_ratio,total_fights,sub_win_ratio,point_win_ratio,decision_win_ratio,n_editions_competed,scored_points_per_fight,suffered_points_per_fight,fights_per_edition,...,n_different_subs,fought_superfight,total_wins,debut_year,female,city,state,country,latitude,longitude
0,Nick Rodriguez,0.700000,10.0,0.100000,0.400000,0.200000,4.0,2.300000,-0.200000,2.500000,...,1,0,7.0,2019,0,Philadelphia,Pennsylvania,USA,39.952724,-75.163526
1,Orlando Sanchez,0.692308,13.0,0.153846,0.153846,0.384615,8.0,-0.384615,-0.461538,1.625000,...,2,0,9.0,2013,0,Los Angeles,California,USA,34.053691,-118.242766
2,Paul Schreiner,0.500000,4.0,0.000000,0.500000,0.000000,2.0,1.250000,-0.500000,2.000000,...,0,0,2.0,2022,0,Santa Cruz,California,USA,37.050096,-121.990590
3,David Terrell,0.750000,4.0,0.250000,0.500000,0.000000,2.0,-1.000000,-1.000000,2.000000,...,1,0,3.0,2003,0,Santa Rosa,California,USA,38.440492,-122.714105
4,Eddie Bravo,0.666667,3.0,0.666667,0.000000,0.000000,2.0,-0.666667,4.666667,1.500000,...,2,0,2.0,2003,0,Santa Ana,California,USA,33.749495,-117.873221
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,Beatriz Mesquita,0.500000,4.0,0.250000,0.250000,0.000000,3.0,0.250000,1.000000,1.333333,...,1,0,2.0,2019,1,Niterói,NaN,Brazil,-22.888400,-43.114700
279,Gabriel Napao,0.750000,4.0,0.250000,0.500000,0.000000,2.0,0.000000,-0.500000,2.000000,...,1,0,3.0,2005,0,Rio de Janeiro,NaN,Brazil,-22.911014,-43.209373
280,A. Cacareco,0.384615,13.0,0.230769,0.153846,0.000000,7.0,-0.076923,-0.153846,1.857143,...,3,0,5.0,2001,0,Rio de Janeiro,NaN,Brazil,-22.911014,-43.209373
289,Rustam Chsiev,0.333333,6.0,0.000000,0.000000,0.333333,5.0,-1.000000,-1.000000,1.200000,...,0,0,2.0,2013,0,Vladikavkaz,NaN,Russia,43.024593,44.682110
291,Olav Einemo,0.666667,3.0,0.000000,0.333333,0.000000,3.0,0.333333,0.666667,1.000000,...,0,0,2.0,2001,0,Oslo,NaN,Norway,59.913330,10.738970

In [16]:
all_fighters_gt_2.describe()

,win_ratio,total_fights,sub_win_ratio,point_win_ratio,decision_win_ratio,n_editions_competed,scored_points_per_fight,suffered_points_per_fight,fights_per_edition,n_weight_classes,...,n_titles,champion,custom_score,n_different_subs,fought_superfight,total_wins,debut_year,female,latitude,longitude
count,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,...,131.000000,131.000000,131.000000,131.000000,131.0,131.000000,131.000000,131.000000,131.000000,131.000000
mean,0.658986,10.801527,0.239573,0.340324,0.068936,5.221374,0.398514,0.040073,2.148064,1.274809,...,0.748092,0.412214,0.950159,1.954198,0.0,7.335878,2010.114504,0.061069,2.748373,-59.085627
std,0.158742,7.784027,0.210108,0.207101,0.103860,3.256449,1.219294,0.865959,1.187157,0.527015,...,1.198355,0.494123,1.719625,1.822351,0.0,5.949287,7.947560,0.240376,27.121496,40.532687
min,0.333333,3.000000,0.000000,0.000000,0.000000,1.000000,-1.000000,-1.000000,1.000000,1.000000,...,0.000000,0.000000,-0.373177,0.000000,0.0,2.000000,1998.000000,0.000000,-37.814245,-157.855676
25%,0.500000,4.500000,0.075000,0.193750,0.000000,3.000000,-0.449495,-0.500000,1.571429,1.000000,...,0.000000,0.000000,0.153367,1.000000,0.0,3.000000,2003.000000,0.000000,-22.911014,-75.271089
50%,0.666667,8.000000,0.222222,0.333333,0.000000,4.000000,0.093023,-0.200000,2.000000,1.000000,...,0.000000,0.000000,0.612343,1.000000,0.0,5.000000,2011.000000,0.000000,-1.204322,-47.158394
75%,0.750000,14.500000,0.353571,0.466667,0.125000,7.000000,0.861905,0.333333,2.354167,1.000000,...,1.000000,1.000000,1.079169,3.000000,0.0,10.500000,2017.000000,0.000000,34.053691,-43.209373
max,1.000000,43.000000,1.000000,1.000000,0.500000,15.000000,6.800000,4.666667,13.000000,4.000000,...,6.000000,1.000000,16.405234,8.000000,0.0,30.000000,2022.000000,1.000000,59.913330,144.963173

In [10]:
all_fighters.to_csv('fighters_wins_gt_2.csv', index=False)

In [11]:
all_fighters['country'].unique()

array(['USA', 'Brazil', 'Australia', 'Canada', 'Wales', 'Russia',
       'Norway'], dtype=object)

In [12]:
all_fighters_filtered = all_fighters[all_fighters['total_fights'] >= 4]
all_fighters_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Index: 129 entries, 0 to 486
Data columns (total 30 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   name                       129 non-null    object
 1   win_ratio                  129 non-null    float64
 2   total_fights               129 non-null    float64
 3   sub_win_ratio              129 non-null    float64
 4   point_win_ratio            129 non-null    float64
 5   decision_win_ratio         129 non-null    float64
 6   n_editions_competed        129 non-null    float64
 7   scored_points_per_fight    129 non-null    float64
 8   suffered_points_per_fight  129 non-null    float64
 9   fights_per_edition         129 non-null    float64
 10  favorite_target            129 non-null    object
 11  most_vulnerable            129 non-null    object
 12  n_weight_classes           129 non-null    int64
 13  main_weight_class          129 non-null    float64
 14  avg_match_importance       129 non-null    float64
 15  highest_match_importance   129 non-null    int64
 16  open_weight_ratio          129 non-null    float64
 17  n_titles                   129 non-null    int64
 18  champion                   129 non-null    int64
 19  custom_score               129 non-null    float64
 20  n_different_subs           129 non-null    int64
 21  fought_superfight          129 non-null    int64
 22  total_wins                 129 non-null    float64
 23  debut_year                 129 non-null    int64
 24  female                     129 non-null    int64
 25  city                       129 non-null    object
 26  state                      39 non-null     object
 27  country                    129 non-null    object
 28  latitude                   129 non-null    float64
 29  longitude                  129 non-null    float64
dtypes: float64(16), int64(8), object(6)
memory usage: 31.2+ KB

In [13]:
all_fighters_filtered['Z-Score'] = (all_fighters_filtered['sub_win_ratio'] - all_fighters_filtered['sub_win_ratio'].mean()) / all_fighters_filtered['sub_win_ratio'].std()
all_fighters_filtered = all_fighters_filtered.sort_values(by='Z-Score', ascending=False)
all_fighters_filtered.head(20)

/var/folders/kf/sp0jlhvs3yb2h_z31jyqkzrc0000gn/T/ipykernel_74413/3481787929.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_fighters_filtered['Z-Score'] = (all_fighters_filtered['sub_win_ratio'] - all_fighters_filtered['sub_win_ratio'].mean()) / all_fighters_filtered['sub_win_ratio'].std()

,name,win_ratio,total_fights,sub_win_ratio,point_win_ratio,decision_win_ratio,n_editions_competed,scored_points_per_fight,suffered_points_per_fight,fights_per_edition,...,fought_superfight,total_wins,debut_year,female,city,state,country,latitude,longitude,Z-Score
29,Kade Ruotolo,1.000000,4.0,1.000000,0.000000,0.000000,1.0,0.000000,0.000000,4.000000,...,0,4.0,2022,0,Huntington Beach,California,USA,33.678334,-118.000016,3.691729
229,Rousimar Palhares,0.750000,4.0,0.750000,0.000000,0.000000,2.0,0.250000,1.500000,2.000000,...,0,3.0,2011,0,Dores do Indaiá,NaN,Brazil,-19.463645,-45.601660,2.478284
183,Davi Ramos,1.000000,4.0,0.750000,0.250000,0.000000,1.0,0.000000,0.000000,4.000000,...,0,4.0,2015,0,Rio de Janeiro,NaN,Brazil,-22.911014,-43.209373,2.478284
221,Marcelo Garcia,0.843750,32.0,0.718750,0.093750,0.000000,9.0,-0.500000,-0.562500,3.555556,...,0,27.0,2003,0,Formiga,NaN,Brazil,-20.464842,-45.426675,2.326604
10,Gordon Ryan,0.952381,21.0,0.714286,0.142857,0.095238,4.0,-0.285714,-0.523810,5.250000,...,0,20.0,2017,0,Monroe Township,New Jersey,USA,40.335756,-74.433446,2.304935
190,Kron Gracie,0.800000,10.0,0.700000,0.100000,0.000000,5.0,-0.800000,-0.600000,2.000000,...,0,8.0,2009,0,Rio de Janeiro,NaN,Brazil,-22.911014,-43.209373,2.235595
8,Giancarlo Bodoni,0.833333,6.0,0.666667,0.166667,0.000000,2.0,0.666667,0.333333,3.000000,...,0,5.0,2022,0,New York City,New York,USA,40.712728,-74.006015,2.073802
171,Roger Gracie,0.923077,13.0,0.615385,0.307692,0.000000,4.0,0.307692,-0.538462,3.250000,...,0,12.0,2003,0,Rio de Janeiro,NaN,Brazil,-22.911014,-43.209373,1.824891
211,Jean Jacques Machado,0.733333,15.0,0.600000,0.133333,0.000000,6.0,0.000000,-0.600000,2.500000,...,0,11.0,1999,0,Rio de Janeiro,NaN,Brazil,-22.911014,-43.209373,1.750217
5,Dean Lister,0.678571,28.0,0.571429,0.107143,0.000000,12.0,-0.464286,0.178571,2.333333,...,0,19.0,2001,0,San Diego,California,USA,32.717420,-117.162772,1.611538
180,Craig Jones,0.642857,14.0,0.571429,0.000000,0.071429,6.0,-0.714286,1.357143,2.333333,...,0,9.0,2017,0,Adelaide,NaN,Australia,-34.928181,138.599931,1.611538
197,Rafael Mendes,0.916667,12.0,0.500000,0.416667,0.000000,4.0,-0.166667,-0.833333,3.000000,...,0,11.0,2009,0,Rio Claro,NaN,Brazil,-22.410011,-47.560393,1.264839
32,Matt Serra,0.750000,4.0,0.500000,0.250000,0.000000,2.0,-1.000000,-1.000000,2.000000,...,0,3.0,2001,0,East Meadow,New York,USA,40.714230,-73.559511,1.264839
185,Diego Oliveira,0.750000,4.0,0.500000,0.250000,0.000000,2.0,-0.750000,-0.750000,2.000000,...,0,3.0,2022,0,São Paulo,NaN,Brazil,-1.204322,-47.158394,1.264839
212,Joao Miyao,0.500000,4.0,0.500000,0.000000,0.000000,2.0,-0.750000,-0.250000,2.000000,...,0,2.0,2013,0,Andirá,NaN,Brazil,-23.049476,-50.231003,1.264839
176,Braulio Estima,0.750000,16.0,0.500000,0.187500,0.000000,6.0,-0.750000,-0.937500,2.666667,...,0,12.0,2005,0,Recife,NaN,Brazil,-8.058493,-34.884819,1.264839
48,Robert Drysdale,0.500000,4.0,0.500000,0.000000,0.000000,3.0,-0.750000,1.250000,1.333333,...,0,2.0,2007,0,Provo,Utah,USA,40.233729,-111.658709,1.264839
217,Kennedy Maciel,0.666667,6.0,0.500000,0.166667,0.000000,4.0,-0.333333,-0.166667,1.500000,...,0,4.0,2019,0,São Paulo,NaN,Brazil,-1.204322,-47.158394,1.264839
253,Antonio Schembri,0.750000,4.0,0.500000,0.250000,0.000000,2.0,-1.000000,-1.000000,2.000000,...,0,3.0,2001,0,Rio de Janeiro,NaN,Brazil,-22.911014,-43.209373,1.264839
251,Alexandre de Freitas,0.684211,19.0,0.473684,0.210526,0.000000,9.0,0.210526,0.421053,2.111111,...,0,13.0,1998,0,Rio de Janeiro,NaN,Brazil,-22.911014,-43.209373,1.137108

In [14]:
all_fighters_filtered.to_csv('fighters_z_scores.csv', index=False)